### ISSUE TITLE
undefined method in styleguide view

### ISSUE THREAD

**Issue by stoplion** [dewski/kss-rails#12]
Getting an..
undefined method `[]' for nil:NilClass
in..
``<h3><%= section.section %> <em><%= section.filename %></em></h3>``

**Comment by dewski** [comment]
Could you paste your `config/routes.rb` file? Or at least confirm it has `mount Kss::Engine => '/styleguide'`.

**Comment by stoplion** [comment]
I can confirm it's in routes file..
mount Kss::Engine => '/kss' if Rails.env.development?

Should this be in routes as well?
mount Kss::Engine => '/styleguide'

**Comment by dewski** [comment]
You changed the original issue after I commented on it. You mentioned you were trying to get `/styleguide`? What happens when you go to `/kss`, and have you restarted the server?

**Comment by stoplion** [comment]
I can navigate to http://localhost:4000/kss/ There it displays some links, Home and Styleguide. Styleguide is where i get the above error on line two  `<h3><%= section.section %> <em><%= section.filename %></em></h3>`

**Comment by dewski** [comment]
I'll need the full backtrace to give a deeper look, `undefined method`[]' for nil:NilClass` and whatever else comes after that.

**Comment by stoplion** [comment]
undefined method `[]' for nil:NilClass

Extracted source (around line #2):

```
1: <div class="styleguide-example">
2:   <h3><%= section.section %> <em><%= section.filename %></em></h3>
3:   <div class="styleguide-description">
4:     <p><%= section.description %></p>
5:     <% if section.modifiers.any? %>
```

Trace of template inclusion: app/views/kss/home/styleguide.html.erb

```
app/views/kss/home/styleguide.html.erb:1:in `_app_views_kss_home_styleguide_html_erb___1281663321373551429_2526041660'
```

**Comment by JAndritsch** [comment]
Sounds like you're might be trying to call "styleguide_block" with a section that doesn't exist in your CSS. For example, if you want to call "styleguide_block '1.0' ", you have to make sure you have "Styleguide 1.0" somewhere in one of your CSS files. That was at least my issue when I first started using this.

**Comment by jankeesvw** [comment]
I've had this questions several times in my team, I have fixed this by adding an error when the section is nil.

![Undefined styleguide](https://f.cloud.github.com/assets/167882/117443/c2c013ea-6c3d-11e2-8dcc-f5255b525060.png)

**Comment by jankeesvw** [comment]
More descriptive error with my this patch: https://github.com/dewski/kss-rails/pull/18

**Comment by jankeesvw** [comment]
This issue can be closed, it's fixed!
