### ISSUE TITLE
rails generate kss:install Not working

### ISSUE THREAD

**Issue by sam3k** [dewski/kss-rails#2]
For those of us who don't know ruby on rails, the installation process might be a bit vague. When I type:

rails generate kss:install Not working

I get:

sage:
  rails new APP_PATH [options]

Options:
  -j, [--javascript=JAVASCRIPT]  # Preconfigure for selected JavaScript library
                                 # Default: jquery
  -J, [--skip-javascript]        # Skip JavaScript files
      [--edge]                   # Setup the application with Gemfile pointing to Rails repository
      [--dev]                    # Setup the application with Gemfile pointing to your Rails checkout
  -G, [--skip-git]               # Skip Git ignores and keeps
  -d, [--database=DATABASE]      # Preconfigure for selected database (options: mysql/oracle/postgresql/sqlite3/frontbase/ibm_db/sqlserver/jdbcmysql/jdbcsqlite3/jdbcpostgresql/jdbc)
                                 # Default: sqlite3
  -b, [--builder=BUILDER]        # Path to a application builder (can be a filesystem path or URL)
      [--old-style-hash]         # Force using old style hash (:foo => 'bar') on Ruby >= 1.9
      [--skip-gemfile]           # Don't create a Gemfile
  -r, [--ruby=PATH]              # Path to the Ruby binary of your choice
                                 # Default: /System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/bin/ruby
  -O, [--skip-active-record]     # Skip Active Record files
      [--skip-bundle]            # Don't run bundle install
  -m, [--template=TEMPLATE]      # Path to an application template (can be a filesystem path or URL)
  -T, [--skip-test-unit]         # Skip Test::Unit files
  -S, [--skip-sprockets]         # Skip Sprockets files

Runtime options:
  -s, [--skip]     # Skip files that already exist
  -p, [--pretend]  # Run but do not make any changes
  -f, [--force]    # Overwrite files that already exist
  -q, [--quiet]    # Supress status output

Rails options:
  -h, [--help]     # Show this help message and quit
  -v, [--version]  # Show Rails version number and quit

Description:
    The 'rails new' command creates a new Rails application with a default
    directory structure and configuration at the path you specify.

```
You can specify extra command-line arguments to be used every time
'rails new' runs in the .railsrc configuration file in your home directory.

Note that the arguments specified in the .railsrc file don't affect the
defaults values shown above in this help message.
```

Example:
    rails new ~/Code/Ruby/weblog

```
This generates a skeletal Rails installation in ~/Code/Ruby/weblog.
See the README in the newly created application to get going.
```

At some point, the docs tell me to re-bundle but not sure what that means. I assume it means, run "rails generate kss:install"

**Comment by dewski** [comment]
You have to have an existing Rails app to use kss-rails with. Have you generated your Rails app already? If you're looking for a standalone example without using Rails, the [KSS repository](https://github.com/kneath/kss/tree/master/example) has a good start for you.

The README is fairly straight forward in this case, a majority of Rails related README's follow this same format. Is there anything in particular you are having trouble understanding?

If you haven't generated your application yet, you'll have to run the following in order:
1. Generate the application, or CD into the one you already generated.
   
   `rails new blog`
2. Add the gem to your Gemfile, you can use your editor for this but for the sake of a command line version:
   
   `echo 'gem "kss-rails", :group => :development' >> Gemfile`
3. This downloads and installs the gem, and also requires it within the Rails application:
   
   `bundle install`
4. This is a Rails only command that can be ran on existing applications, it's just a hook Rails provides for gems to add their own installers or related generators:
   
   `rails generate kss:install`
5. This starts the server, once that finishes copy the URL and you should be able to access it at something like `http://localhost:3000/kss`:
   
   `rails server`

**Comment by sam3k** [comment]
I see. It was my impression that this will work for any app even if it is not a Rails app. Too bad. =/

Thanks for clearing this up Garrett.
