### ISSUE TITLE
Creating new sections in the left submenu

### ISSUE THREAD

**Issue by lloydmeta** [dewski/kss-rails#24]
Hi there,

I'm trying to get this integrated into our project for our front-end guys to play around with. Appreciate all the hard work thats gone into it !

I'm wondering if it's possible to add links to the left hand side submenu to lead to different sections like the way [Github does their styleguide](https://github.com/styleguide/css/1.0) without messing around with routes.rb? 

I've tried looking around but couldn't really find anything.

Thanks in advance !

Lloyd

**Comment by dewski** [comment]
Unfortunately there is no solution provided by kss-rails. We've left it open for you to be able to add your own routes and override the provided templates so you can add whatever sections to the styleguide that you like.

You can do something like below which will get you 90% of the way there.

``` ruby
Rails.application.routes.draw do
  get '/styleguide/1.0' => 'styleguide#links'
end
```

``` ruby
class StyleguideController < Kss::ApplicationController
  def links

  end
end
```

**Comment by lloydmeta** [comment]
Ah got it. Thanks !
